### ISSUE TITLE
Respecced character disappears, Mythic levels doesn't show.

### ISSUE THREAD

**Issue by BrutaleBent** [BarleyFlour/RespecMod#2]
Hey again, now I had a little free time to test it!

Tried with Woljif again, and noted a few things:

1. If he's buffed when respeccing, stat increases (those at 4/8/12/etc) doesn't "stick".
2. He gains a red icon upon respec, and if I save and reload, he's not part of the party anymore, even if still targetable, and able to use him that way.
3. Mythic levels seem to be gone permanently.

Tried on latest version (1.3).

**Comment by BarleyFlour** [comment]
1 & 3 should be fixed in 1.5, wasnt able to reproduce 2 though.

**Comment by BrutaleBent** [comment]
Right, I'll check once I get home from work, see if I can find other things!

Would you be interested in a savegame, if 2. still happens?

**Comment by BarleyFlour** [comment]
That and difficulty settings would be nice yeah.

**Comment by BrutaleBent** [comment]
Now stats and mythic levels seem to work, so that's ace! ;)

However, 2. still remains an issue. If I respec anyone, they ultimately get removed from the party, permanently - not even available if I go to base, then back to map (unavaible to select).

I also found I can readd them using ToyBox after I reload a saved game, and then it seems to be working after that - but that's not really optimal, imo.

Saves and screenshots here: https://mega.nz/folder/ZkE02RqR#EZKeHJFDlt-IxQ_gOOem-A

**Comment by BarleyFlour** [comment]
Should be fixed with 1.6 but i would appreciate if you try it out and see if it works.

**Comment by BrutaleBent** [comment]
Did a really quick non thorough test before work, and there was some fuckery with me being unable to select things and "Next" button stayed greyed out. It was such as classes and "race" (in Woljjifs case, type of tiefling), and had to click around a lot to be able to click next.

However, after a reload, it seemed to work, for some reason. So I'm still on the fence about it being an issue with the mod, or an issue with me/my PC - I'll test further once I get home from work.

In any case; awesome work so far, mate! :)

**Comment by BrutaleBent** [comment]
Still short on time today, but there's still some fuckery about, with buttons sometimes being greyed out.

Also found that spellslots aren't cleared, so if you respec with abundant casting, you keep those spellslots in that spellbook if you get the same spellbook.

**Comment by BarleyFlour** [comment]
Spellslot thing was simple enough, cant seem to reproduce the buttons being greyed out, do you have any other mods on?

**Comment by BrutaleBent** [comment]
Nice! Also can't seem to reliably reproduce it either - it just happens.

Though, I did have weapon focus plus mod on, when testing - though, it shouldn't interfere afaik. :| Anyways, it's not that important, as it's easily bypassable for me. :)

**Comment by BrutaleBent** [comment]
I tried with no other mods, still occsionally happens.

**Comment by BrutaleBent** [comment]
Uploaded som screenshots, but not really sure it shows anything: https://mega.nz/folder/RosgzIbK#97cTJpsNYvydNkzU4TTUFA

I can click around till it happens, then I click till I get something I can actually select, and can then proceed. Can happen in racial too, and then you have to redo the respec.

In the SS series, what happened, was me clicking on inquisitor, couldn't select, clicked magus, could select, clicked rogue, could select, clicked knife master, couldn't select. 

Not sure if it's any help, but I tried! ;)

**Comment by BarleyFlour** [comment]
I remember having that bug in the basegame, so i think its not related to the mod, but iirc you can click on the next step at the top of the screen (so ability score if you're on racial) and the spellslot fix is out now.

**Comment by BrutaleBent** [comment]
Alright, guess that's all then for the first part.

Great job, mate! :D
