### ISSUE TITLE
Multiple respec causes the increase of bab

### ISSUE THREAD

**Issue by lizkes** [BarleyFlour/RespecMod#7]
I respec camellia many times, every time I respec will increase her bab.
In the picture below, she is a level 3 shaman with 6 bab
![图片](https://user-images.githubusercontent.com/20457790/126028821-66ea1592-455a-4484-a778-c3484c4299f7.png)

**Comment by BarleyFlour** [comment]
I cant seem to be able to recreate this, could you tell me how to recreate it and save me your save?

**Comment by lizkes** [comment]
As long as you keep respecing the same class, such bug will appear. If you choose a different class, bab will reset.

**Comment by lizkes** [comment]
Here is my [save file](https://we.tl/t-4g0X65FbaU) if you need

**Comment by templer10** [comment]
Love your work. Any eta on solving this?

**Comment by BarleyFlour** [comment]
This should be fixed as of 1.01.0 but im not 100%

**Comment by lizkes** [comment]
I just used version 1.01.0, unfortunately this bug still exists. 
In order to reproduce this bug, at least two levels of companion need to perform more than two respecs. In fact, I found that the same class is not required

**Comment by templer10** [comment]
yea - not fixed. attached is a save with the bug already in place. any respect will just add more BAB. 
[Manual_68_Market_Square__20_Gozran__IV__4710__21_07_17.zip](https://github.com/BarleyFlour/RespecMod/files/6835260/Manual_68_Market_Square__20_Gozran__IV__4710__21_07_17.zip)

**Comment by BarleyFlour** [comment]
Ok now it should be fixed for real, i hope, i was able to recreate it and the fix seems to make me unable to recreate it, so... should work now.

**Comment by templer10** [comment]
will check it out. small unrelated question, would it be possible for you to add an option for a full respect of a companion that doesnt get rid of it's picture/voice - i didnt try it out but i have a feeling that doing it on a companion as is will break something in it's quests etc (the option exists in the kingmaker respect mod).

**Comment by BarleyFlour** [comment]
> will check it out. small unrelated question, would it be possible for you to add an option for a full respect of a companion that doesnt get rid of it's picture/voice - i didnt try it out but i have a feeling that doing it on a companion as is will break something in it's quests etc (the option exists in the kingmaker respect mod).

I'm going to bed rn but it should be possible so i'll take a look tomorrow.

**Comment by lizkes** [comment]
This bug has been fixed in version 1.01.1, nice work!
